
service: kotlin-graalvm-custom-runtime-talk

provider:
  name: aws
  runtime: java8
  region: eu-central-1

package:
  artifact: build/libs/package-1.0.jar

functions:
  hello:
    handler: com.github.md.Handler
    events:
      - http:
          path: hello/{name}
          method: get