
service: kotlin-graalvm-custom-runtime-talk

provider:
  name: aws
  runtime: java8
  region: eu-central-1

package:
  individually: true

functions:
  hello:
    handler: com.github.md.Handler
    events:
      - http:
          path: hello/{name}
          method: get
    package:
      artifact: build/libs/package-1.0.jar
  hello-runtime:
    handler: com.github.md.Handler
    runtime: provided
    events:
      - http:
          path: hello-runtime/{name}
          method: get
    package:
      artifact: build/package/bundle.zip